### ISSUE TITLE
Does not write assets

### ISSUE THREAD

**Issue by ik0r** [gajus/write-file-webpack-plugin#14]
If I use with html-webpack-plugin to auto insert file hash to html files.

when use with devserver, only js files are force write to disk, html is not wrote

**Comment by gajus** [comment]
There is already a PR that addresses this.

https://github.com/gajus/write-file-webpack-plugin/pull/13

The problem I have with it (apart from the reason I gave in the closing message) is that it is using `stats.compilation.assets` instead of `stats.compilation.chunks` and I am unable to find documentation explaining the difference.

@MichalBures How did you learn about `stats.compilation.assets` in the first place?

**Comment by MichalBures** [comment]
As I said in the PR the reason for `compilation.assets` instead of `compilation.chunks` is because that's what the `copy-webpack-plugin` plugin uses. And when I compared them `compilation.assets` had all the chunk files, so they were easily exchanged.

A small issue with this is that webpack uses `compilation.assets` for its hot update files which need to be filtered out, but that can be simply done by not writing files containing `'hot-update'` string.

FYI, I've been using this approach for several weeks now and I haven't had any issues. Furthermore several different plugins are also using `compilation.assets` without any apparent problems. So I guess it's safe to use, although some official documentation would be nice.

**Comment by gajus** [comment]
> FYI, I've been using this approach for several weeks now and I haven't had any issues. Furthermore several different plugins are also using compilation.assets without any apparent problems. So I guess it's safe to use, although some official documentation would be nice.

Thank you. Those are useful insights.

**Comment by gajus** [comment]
@MichalBures, @Treri It should work with assets now.

Unfortunately, due to the nature of the script, I cannot think of how to write tests cases. If you have suggestions, please open an issue.
